# Generated by Django 3.1.7 on 2021-04-24 10:51

from django.db import migrations, models
import markdownx.models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Project_technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Tagulous_Project_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('year', models.CharField(max_length=255)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='An integer that represents a priority for displaying the project. A value of 1 will be displayed higher than a value of 2.', verbose_name='Display Priority')),
                ('thumbnail', models.ImageField(default='Default_project_thumbnail.png', upload_to='Projects thumbnails')),
                ('banner', models.ImageField(default='Default_project_banner.png', upload_to='Projects banners')),
                ('hyperlink', models.URLField(blank=True, help_text="Redirects to project's external webpage.", verbose_name='External hyperlink')),
                ('content', markdownx.models.MarkdownxField()),
                ('categories', tagulous.models.fields.TagField(_set_tag_meta=True, case_sensitive=False, help_text='Enter a comma-separated tag string', max_count=3, space_delimiter=False, to='projects.Tagulous_Project_categories')),
                ('technologies', tagulous.models.fields.TagField(_set_tag_meta=True, case_sensitive=False, help_text='Enter a comma-separated tag string', space_delimiter=False, to='projects.Tagulous_Project_technologies')),
            ],
        ),
    ]
