# Generated by Django 3.1.7 on 2021-03-20 11:47

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
