# Generated by Django 3.1.7 on 2021-03-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='Default_project_thumbnail.jpg', upload_to='Projects thumbnails'),
        ),
    ]
