# Generated by Django 3.1.7 on 2021-03-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='Default_project_thumbnail.png', upload_to='Projects thumbnails'),
        ),
    ]
