# Generated by Django 3.1.7 on 2021-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210330_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner',
            field=models.ImageField(default='Default_project_banner.png', upload_to='Projects banners'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, help_text='An integer that represents a priority for displaying the project. A value of 1 will be displayed higher than a value of 2.', verbose_name='Display Priority'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
