# Generated by Django 3.1.7 on 2021-04-02 10:24

from django.db import migrations, models
import django.utils.timezone
import markdownx.models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Post_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Title')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('thumbnail', models.ImageField(default='Default_blogpost_thumbnail.png', upload_to='Blog thumbnails')),
                ('banner', models.ImageField(default='Default_project_banner.png', upload_to='Blog banners')),
                ('content', markdownx.models.MarkdownxField()),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, case_sensitive=False, help_text='Enter a comma-separated tag string', space_delimiter=False, to='blog.Tagulous_Post_tags')),
            ],
        ),
    ]
