# Generated by Django 3.1.7 on 2021-04-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='Default_project_banner.svg', upload_to='BlogBanners'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='Default_blogpost_thumbnail.svg', upload_to='BlogThumbnails'),
        ),
    ]
