# Generated by Django 3.1.7 on 2021-04-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210426_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='Default_blogpost_banner.svg', upload_to='BlogBanners'),
        ),
    ]
