# Generated by Django 3.1.7 on 2021-04-15 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20210331_0913'),
        ('blog', '0003_auto_20210402_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publications.myinfo'),
            preserve_default=False,
        ),
    ]
