# Generated by Django 3.1.7 on 2021-04-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Example: PhD in Engineering Science', max_length=100)),
                ('dates', models.CharField(default='', help_text='Example: 2017-2019', max_length=60)),
                ('institution', models.CharField(default='', help_text='Example: University of Oxford, UK', max_length=100)),
                ('hyperlink', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Example: Postdoctoral researcher', max_length=100)),
                ('dates', models.CharField(default='', help_text='Example: 2020-2021', max_length=60)),
                ('company', models.CharField(default='', help_text='Example: University of Oxford, UK', max_length=100)),
                ('hyperlink', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Example: Data Science and Visualisation', max_length=100)),
                ('description', models.CharField(default='', help_text='Example: Analysis libraries: pandas, numpy', max_length=255)),
            ],
        ),
    ]
