# Generated by Django 3.1.7 on 2021-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Example: PhD in Engineering Science', max_length=100)),
                ('start_date', models.PositiveSmallIntegerField(default=2020)),
                ('end_date', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('institution', models.CharField(default='', help_text='Example: University of Oxford, UK', max_length=100)),
                ('hyperlink', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'degree',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Example: Postdoctoral researcher', max_length=100)),
                ('start_date', models.PositiveSmallIntegerField(default=2020)),
                ('end_date', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('company', models.CharField(default='', help_text='Example: University of Oxford, UK', max_length=100)),
                ('hyperlink', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Example: Data Science and Visualisation', max_length=100)),
                ('description', models.CharField(default='', help_text='Example: Analysis libraries: pandas, numpy', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_initials', models.CharField(default='', help_text='Example: J Doe', max_length=50, verbose_name='My Initials')),
                ('email', models.EmailField(default='', help_text="Email recipient for 'contact me' form", max_length=254)),
                ('profile_pic', models.ImageField(default='Default_profile_pic.png', help_text='Picture displayed at home page', upload_to='Profile_pics')),
                ('cv', models.FileField(help_text='Resume/CV to be made available for download at about page', upload_to='CV')),
            ],
            options={
                'verbose_name': 'My Info',
                'verbose_name_plural': 'My Info',
            },
        ),
    ]
