# Generated by Django 3.1.7 on 2021-04-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='cv',
            field=models.FileField(default='Default_CV.pdf', help_text='Resume/CV to be made available for download at about page', upload_to='CV'),
        ),
    ]
