# Generated by Django 3.1.7 on 2021-04-05 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210405_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='date_start',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='date_end',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
