# Generated by Django 3.1.7 on 2021-04-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210405_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='dates',
        ),
    ]
