# Generated by Django 3.1.7 on 2021-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_education_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
    ]
