# Generated by Django 3.1.7 on 2021-04-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210405_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='dates',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.PositiveSmallIntegerField(blank=True, default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
    ]
