# Generated by Django 3.1.7 on 2021-04-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210405_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
