# Generated by Django 3.1.7 on 2021-04-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210405_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
