# Generated by Django 3.1.7 on 2021-04-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BK', 'Book'), ('AR', 'Article'), ('CF', 'Conference Paper'), ('BC', 'Book Chapter'), ('PT', 'Patent')], default='AR', max_length=2, verbose_name='Publication type')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('year', models.CharField(max_length=50, verbose_name='Publishing Year')),
                ('authors', models.CharField(default='', help_text="Example: 'F. Author, J. Doe.'. A name can be highlighted by enclosing it in html 'strong' tags: <strong>J. Doe</strong>.", max_length=255, verbose_name='Authors')),
                ('publisher', models.CharField(default='', help_text='Journal, publisher, patent provider, etc.', max_length=200, verbose_name='Publisher')),
                ('link', models.URLField(blank=True, help_text='Redirects user to publication. (e.g. DOI for article)', verbose_name='External hyperlink')),
                ('my_info', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.myinfo')),
            ],
            options={
                'ordering': ['kind', 'year', 'title'],
            },
        ),
    ]
