# Generated by Django 3.1.7 on 2021-03-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(help_text="Example: 'F. Author, J. Doe.'. A name can be highlighted with an html emphasis tag: <em>J. Doe</em>.", max_length=255, verbose_name='Authors')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('year', models.IntegerField(verbose_name='Publishing Year')),
                ('link', models.CharField(default='#', help_text='Redirects user to publication. (e.g. DOI for article)', max_length=200, verbose_name='External hyperlink')),
                ('type', models.CharField(choices=[('BK', 'Book'), ('AR', 'Article'), ('CF', 'Conference Paper'), ('BC', 'Book Chapter'), ('PT', 'Patent')], default='AR', max_length=2, verbose_name='Publication type')),
                ('publisher', models.CharField(default='', help_text='Journal, publisher, patent provider, etc.', max_length=200, verbose_name='Publisher')),
            ],
            options={
                'ordering': ['type', 'year', 'title'],
            },
        ),
    ]
