# Generated by Django 3.1.7 on 2021-03-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['kind', 'year', 'title']},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='type',
            new_name='kind',
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(default='', help_text="Example: 'F. Author, J. Doe.'. A name can be highlighted with html tags: <strong>J. Doe</strong>.", max_length=255, verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, help_text='Redirects user to publication. (e.g. DOI for article)', verbose_name='External hyperlink'),
        ),
    ]
