# Generated by Django 3.1.7 on 2021-03-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20210313_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
