# Generated by Django 3.1.7 on 2021-03-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20210330_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myinfo',
            options={'verbose_name': 'My Info', 'verbose_name_plural': 'My Info'},
        ),
        migrations.AddField(
            model_name='publication',
            name='my_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publications.myinfo'),
        ),
    ]
