# Generated by Django 3.1.7 on 2021-03-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20210330_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.CharField(max_length=50, verbose_name='Publishing Year'),
        ),
    ]
