# Generated by Django 3.1.7 on 2021-03-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20210331_0901'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagulous_publication_authors',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='my_initials',
            field=models.CharField(help_text='Example: J Doe', max_length=50, verbose_name='My Initials'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.CharField(default='', help_text="Example: 'F. Author, J. Doe.'. A name can be highlighted by enclosing it in html 'strong' tags: <strong>J. Doe</strong>.", max_length=255, verbose_name='Authors'),
        ),
        migrations.DeleteModel(
            name='Tagulous_MyInfo_my_initials',
        ),
        migrations.DeleteModel(
            name='Tagulous_Publication_authors',
        ),
    ]
