# Generated by Django 3.1.7 on 2021-03-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20210331_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='my_initials',
            field=models.CharField(default='', help_text='Example: J Doe', max_length=50, verbose_name='My Initials'),
        ),
    ]
