# Generated by Django 3.1.7 on 2021-04-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20210331_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='myinfo',
            name='profile_pic',
            field=models.ImageField(default='Default_project_pic.png', upload_to='Profile_pics'),
        ),
    ]
